bot/urls.py
from django.conf.urls import url

from .views import get_question, set_answer


urlpatterns = [
    url(r'get_question$', get_question, name='bot_get_question'),
    url(r'set_answer/$', set_answer, name='bot_set_answer'),
]

content/urls.py
from django.conf.urls import url


from content.views import (LandingView, PortfolioListView, PortfolioDetailView,
                           ContactsView, order_create_view, attachment_view)


urlpatterns = [
    url(r'^$', LandingView.as_view(), name='landing'),
    url(r'^portfolio/$', PortfolioListView.as_view(), name='portfolio'),
    url(r'^portfolio/(?P<pk>[0-9_-]+)/$',
        PortfolioDetailView.as_view(),
        name='portfolio_detail'),
    url(r'^contacts/$', ContactsView.as_view(), name='contacts'),
    url(r'^order/$', order_create_view, name='create_order'),
    url(r'attachment/(?P<filename>[^/]+)/$',
        attachment_view,
        name='attachment_view'),
]

unruled/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.contrib.staticfiles.urls import static

urlpatterns = [
    url(r'^', include('content.urls', namespace='content')),
    url(r'^bot/', include('bot.urls', namespace='bot')),
    url(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

content/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.urls import reverse
from django.db import models
from django.contrib.contenttypes.models import ContentType
from ckeditor.fields import RichTextField
import datetime
from mptt.models import MPTTModel, TreeForeignKey, TreeManager
import os
from django.utils.html import format_html


class ExtraBlockQuerySet(models.QuerySet):
    def active(self, *args, **kwargs):
        kwargs['is_active'] = True
        return self.filter(*args, **kwargs)


class ExtraBlock(models.Model):

    class Meta:
        verbose_name = 'Дополнительный блок'
        verbose_name_plural = 'Дополнительные блоки'
        ordering = ('order',)

    name = models.CharField('Имя блока', max_length=120)
    html = RichTextField('Содержание блока')
    order = models.PositiveIntegerField('Порядок', default=1)
    is_active = models.BooleanField('Отображать на сайте', default=True)

    objects = ExtraBlockQuerySet.as_manager()

    def __unicode__(self):
        return self.name


class PortfolioManager(models.Manager):

    def last_added(self):
        return self.all()[:3]

    def indicator(self):
        period_start = datetime.datetime.today()-datetime.timedelta(days=30)
        return self.filter(release_date__gte=period_start).count()


class Portfolio(models.Model):
    class Meta:
        ordering = ('-release_date',)
        verbose_name = verbose_name_plural = "Портфолио"

    name = models.CharField("Имя клиента", max_length=255)
    image = models.ImageField("Скриншот", upload_to="portfolio", default="/img/not-found.png")
    url = models.URLField("Ссылка на сайт", blank=True, null=True)
    release_date = models.DateField("Дата релиза")
    short_description = models.TextField("Краткое описание проекта")
    detailed_description = models.TextField("Подробное описание проекта")

    objects = PortfolioManager()

    def __unicode__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('content:portfolio_detail', kwargs={"pk": self.id})


class MenuItemQuerySet(models.QuerySet):

    def header_items(self, *args, **kwargs):
        kwargs['position'] = MenuItem.PositionChoices.HEADER
        return self.filter(*args, **kwargs).order_by('order')

    def footer_items(self, *args, **kwargs):
        kwargs['position'] = MenuItem.PositionChoices.FOOTER
        return self.filter(*args, **kwargs).order_by('order')


class MenuItem(MPTTModel):
    class Meta:
        verbose_name = "Пункт меню"
        verbose_name_plural = "Пункты меню"
        ordering = ('order', )

    class MPTTMeta:
        order_insertion_by = ['order']

    class PositionChoices:
        HEADER = 'header'
        FOOTER = 'footer'
        _CHOICES = (
            (HEADER, 'Header'),
            (FOOTER, 'Footer')
        )

    parent = TreeForeignKey('self',
                            verbose_name='Родитель',
                            related_name='subitems',
                            blank=True, null=True)

    url = models.CharField("Ссылка", max_length=120)
    title = models.CharField("Название", max_length=255)
    linked_model = models.ForeignKey(ContentType,
                                     verbose_name="Тип контента",
                                     help_text="Определяет индикатор",
                                     blank=True,
                                     null=True)
    position = models.CharField("Положение",
                                max_length=10,
                                default=PositionChoices.HEADER,
                                choices=PositionChoices._CHOICES,
                                db_index=True)

    order = models.PositiveIntegerField('Порядок', default=0)

    objects = TreeManager.from_queryset(MenuItemQuerySet)()
    objects.use_for_related_fields = True

    def __unicode__(self):
        return '{} - {}'.format(self.position.capitalize(), self.title)

    @property
    def indicator(self):
        try:
            return self.linked_model.model_class().objects.indicator()
        except AttributeError:
            return None


class UnruledNumbers(models.Model):
    class Meta:
        verbose_name = verbose_name_plural = "Unruled в цифрах"

    number = models.IntegerField("Значение")
    measure_unit = models.CharField("Единица измерения", max_length=120)

    def __unicode__(self):
        return "{} {}".format(self.number, self.measure_unit)


class Client(models.Model):
    class Meta:
        verbose_name = "Клиент"
        verbose_name_plural = "Клиенты"

    name = models.CharField("Название", max_length=255)
    logo = models.ImageField("Логотип", upload_to="clients")

    def __unicode__(self):
        return self.name


class WhyUnruled(models.Model):
    class Meta:
        verbose_name = verbose_name_plural = 'Блок "Почему Unruled?"'

    text = models.TextField("Подпись")
    icon = models.ImageField("Иконка", upload_to="icons")

    def __unicode__(self):
        return self.text


class PortfolioImage(models.Model):
    class Meta:
        verbose_name = "Изображение галереи портфолио"
        verbose_name_plural = "Изображения галереи портфолио"

    portfolio = models.ForeignKey(Portfolio,
                                  related_name='images',
                                  verbose_name="Портфолио")
    image = models.ImageField("Картинка", upload_to="portfolio")

    def __unicode__(self):
        return '{} - {}'.format(self.portfolio.name, self.image.name)


class Message(models.Model):
    class Meta:
        ordering = ['-created_dt']
        verbose_name = 'Сообщение'
        verbose_name_plural = 'Сообщения'

    created_dt = models.DateTimeField('Время создания', auto_now_add=True)
    name = models.CharField('Имя', max_length=50)
    email = models.EmailField('Адрес электронной почты')
    text = models.TextField('Текст сообщения')

    def __unicode__(self):
        return '{} {}'.format(self.created_dt, self.email)


class Order(models.Model):
    class Meta:
        ordering = ('-created_dt',)
        verbose_name = "Заказ"
        verbose_name_plural = "Заказы"

    name = models.CharField("Имя клиента",
                            max_length=255)
    phone_or_email = models.CharField("Телефон или e-mail",
                                      max_length=255)

    description = models.TextField("Описание проекта",
                                   blank=True)
    attachment = models.FileField("Требования/тех задание",
                                  upload_to="orders",
                                  blank=True)

    portfolio = models.ForeignKey(Portfolio,
                                  verbose_name="Портфолио",
                                  blank=True, null=True)
    created_dt = models.DateTimeField("Дата создания",
                                      auto_now_add=True)

    def __unicode__(self):
        return '{} {}'.format(self.name, self.phone_or_email)

    def download_attachment(self):
        if self.attachment:
            url = reverse('content:attachment_view',
                          args=[os.path.basename(self.attachment.file.name)])
            return format_html('<a class="button" href="' + url + '">Скачать</a>')

    download_attachment.short_description = 'Требования/тех задание'

content/forms.py
# -*- coding: utf-8 -*-
from django.conf import settings
from django.template.defaultfilters import filesizeformat
from django import forms
from .models import Message, Order
import magic


class MessageForm(forms.ModelForm):
    class Meta:
        model = Message
        fields = ('name', 'email', 'text')


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        exclude = ('created_dt', )

    def clean_attachment(self):
        attachment = self.cleaned_data['attachment']
        if attachment:
            # check type
            file_type = magic.from_buffer(attachment.read(1024), True)

            if file_type not in settings.UPLOAD_ALLOWED_MIME_TYPES:
                raise forms.ValidationError(
                    'Данный тип файла не поддерживается'
                )

            if attachment.size > settings.MAX_UPLOAD_SIZE:

                raise forms.ValidationError(
                    'Размер файла требований '
                    'превышает максимально допустимый '
                    '({})'.format(filesizeformat(settings.MAX_UPLOAD_SIZE))
                )
        return attachment

content/views.py
# -*- coding: utf-8 -*-
from django.views.decorators.http import require_POST
from django.views.generic import TemplateView, ListView, DetailView
from .models import (ExtraBlock, UnruledNumbers, Client, WhyUnruled,
                     Portfolio)
from .forms import MessageForm, OrderForm
from django.http import (JsonResponse, HttpResponseBadRequest,
                         HttpResponse, HttpResponseForbidden)
import json
import os
from django.utils.encoding import smart_str
from django.conf import settings


class LandingView(TemplateView):
    template_name = 'content/landing.html'

    def get_context_data(self, **kwargs):
        kwargs['extra_blocks'] = ExtraBlock.objects.active()
        kwargs['unruled_numbers'] = UnruledNumbers.objects.all()
        kwargs['clients'] = Client.objects.all()
        kwargs['why_unruled'] = WhyUnruled.objects.all()
        kwargs['portfolio_list'] = Portfolio.objects.last_added()
        return super(LandingView, self).get_context_data(**kwargs)


class PortfolioListView(ListView):
    queryset = Portfolio.objects.all()
    context_object_name = 'portfolio_list'
    template_name = 'content/portfolio_list.html'
    paginate_by = 6


class PortfolioDetailView(DetailView):
    model = Portfolio
    template_name = 'content/portfolio.html'
    context_object_name = 'portfolio'

    def get_context_data(self, **kwargs):
        context = super(PortfolioDetailView, self).get_context_data(**kwargs)

        # set previous and next page
        try:
            context['prev_portfolio'] = self.object.get_previous_by_release_date().get_absolute_url()
        except Portfolio.DoesNotExist:
            context['prev_portfolio'] = None

        try:
            context['next_portfolio'] = self.object.get_next_by_release_date().get_absolute_url()
        except Portfolio.DoesNotExist:
            context['next_portfolio'] = None

        context['left_menu_hide'] = True

        return context


class ContactsView(TemplateView):
    template_name = 'content/contacts.html'

    def post(self, request):
        if not request.is_ajax():
            return HttpResponseBadRequest()

        # parse data
        try:
            data = json.loads(request.body)
        except ValueError:
            return JsonResponse({'status': 'error',
                                 'message': 'Invalid request body'})

        form = MessageForm(data)
        if form.is_valid():
            form.save()
            return JsonResponse({'status': 'ok',
                                 'message': u'Ваше сообщение отправлено, '
                                            u'с Вами свяжется наш сотрудник'})

        return JsonResponse({'status': 'error'})


@require_POST
def order_create_view(request):
    form = OrderForm(request.POST, request.FILES)

    if form.is_valid():
        form.save()

        return JsonResponse({'status': 'ok',
                             'message': u'Ваше сообщение отправлено, '
                                        u'с Вами свяжется наш сотрудник'})

    return JsonResponse({'status': 'error'})


def attachment_view(request, filename):
    """Allow to download files only for authorized users"""
    if request.user.is_authenticated:
        response = HttpResponse()
        url = os.path.join('/media/orders/', filename)
        response['Content-Disposition'] = 'attachment; filename=%s' % smart_str(filename)
        path = os.path.join(settings.MEDIA_ROOT, 'orders/', filename)
        length = os.path.getsize(path)
        response['Content-Length'] = str(length)
        response['X-Accel-Redirect'] = url
        return response

    else:
        return HttpResponseForbidden("Restricted Access")

content/templates/content/contacts.html
{% extends "base.html" %}
{% block content %}
  <!--contacts start-->
  <section class="contacts-section" id="contact">

      <!--google map start-->
      <section class="google-map">
          <div class="map" id="google-map" data-address="{{ conf.google_maps_address }}"></div>
      </section>
      <!--google map end-->

      <!--contacts form start-->

      <div class="form-container">
          <div class="container">
              {% include 'content/partials/contact_form.html' %}
              <div class="contacts-info">
                  <div class="contact-wrap">
                      <p><b>Контактный телефон: </b></p>
                      <p>{{ conf.phone }}</p>
                  </div>
                  <div class="contact-wrap">
                      <p><b>E-mail: </b></p>
                      <p><a href="mailto:{{ conf.email }}">{{ conf.email }}</a></p>
                  </div>
                  <div class="contact-wrap">
                      <p><b>Адрес: </b></p>
                      <p>{{ conf.address }}</p>
                  </div>
              </div>
          </div>


      </div>

      <!--contacts form end-->
  </section>
  <!--contacts end-->
  {% include 'content/partials/popup_response_form.html' %}
{% endblock %}

{% block scripts %}
  <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDlgAx5uM4UtPMSzDaVToeNGqe9uNZqRP4"></script>
  {{ block.super }}
{% endblock %}

content/templates/content/landing.html
{% extends 'base.html' %}
{% load static from staticfiles %}

{% block bot_header %}
  <li class="masonic-eye" id="bot-open"><a href="#"></a></li>
{% endblock %}

{% block bot_body %}
{% include 'bot/bot.html' %}
{% endblock %}

{% block left_menu %}
      <a href="{% if conf.show_about %}#history{% else %}#!{% endif %}">История</a>
      <a href="{% if conf.show_clients %}#clients{% else %}#!{% endif %}">Клиенты</a>
      <a href="{% if conf.show_portfolio %}#portfolio{% else %}{% url 'content:portfolio' %}{% endif %}">Портфолио</a>
      <a href="{% if conf.show_contacts %}#contact{% else %}{% url 'content:contacts' %}{% endif %}">Контакты</a>
{% endblock %}

{% block content %}

  {% if conf.show_about %}
  <section class="history-section" id="history">
    <div class="container">
      <!--history block start-->
      <div class="tagline">
        <p><span></span>{{ conf.about_slogan }}</p>
        <h2>{{ conf.about_slogan_text }}</h2>
      </div>
      <hr width="2px" color="#fff" size='429px'>
      <div class="history">
          <h2>ИСТОРИЯ</h2>
          {{ conf.about_text|linebreaks }}
      </div>

      <p class="unruled-in-numbers">Unruled в цифрах</p>
      <div class="statistics">
          {% for number in unruled_numbers %}
          <div class="statistics__block">
              <p>{{ number.number }}</p>
              <p>{{ number.measure_unit }}</p>
          </div>
        {% endfor %}
      </div>
    </div>
  </section>
  <!--history block end-->
  {% endif %}

  {% if conf.show_clients %}
  <!--clients start-->
  <section class="clients-section" id="clients">
      <div class="container">
          <h2 class="clients-section__title">НАШИ КЛИЕНТЫ</h2>
          <div class="clients-wrap">
              {% for client in clients %}
                <a href=#! class="clients-section__client client shadow" style="background-image:url('{{ client.logo.url }}');"></a>
              {% endfor %}
              <a href="#!" class="more-clients-btn">Смотреть еще</a>
          </div>
      </div>
  </section>
  <!--clients end-->
  {% endif %}


  {% if conf.show_why_unruled %}
  <!--why unruled start-->
  <section class="unruled">
      <div class="container">
          <h2 class="unruled__title">ПОЧЕМУ UNRULED</h2>
          <div class="advantages">
            {% for reason in why_unruled %}
              <div class="advantage">
                  <p class="advantage__icon" style="background-image: url('{{ reason.icon.url }}');"></p>
                  <p class="advantage__text">{{ reason.text }}</p>
              </div>
            {% endfor %}
          </div>
          <a href="#!" class="open-project-btn pop-up-form-open">Открыть проект</a>
      </div>
  </section>

  <!--why unruled end-->
  {% endif %}


  {% if conf.show_portfolio %}
  <!--portfolio start-->
  <section class="portfolio-section" id="portfolio">
      <div class="container">
          <h2 class="portfolio-section__title">ПОРТФОЛИО</h2>

          <div class="portfolio">
              {% for item in portfolio_list %}
              <div class="portfolio__project project">
                  <p class="project__img shadow" style="background-image:url({{ item.image.url }})"></p>
                  <div class="project__info">
                      <p class="project__info__title">{{ item.name }}</p>
                      <p class="project__info__text">{{ item.short_description }}</p>
                      <p class="project__btns">
                          <a href="{{ item.get_absolute_url }}" class="project__btn project__btn-more">Посмотреть</a>
                          <a href="#!" class="project__btn project__btn-buy pop-up-form-open" data-project-id="{{ item.id }}"></a>
                      </p>
                  </div>
              </div>
            {% endfor %}

              <a href="{% url 'content:portfolio' %}" class="portfolio__btn-more">Смотреть еще</a>
          </div>

      </div>
  </section>

  <!--portfolio end-->
  {% endif %}

  {% if extra_blocks %}
    <!-- extra block start -->
    {% for extra_block in extra_blocks %}

    <div class="extra-block">
        <div class="container">
          {{ extra_block.html|safe }}
        </div>
    </div>
    {% endfor %}
    <!-- extra block end -->
  {% endif %}

  {% if conf.show_contacts %}
  <!--contacts start-->
  <section class="contacts-section" id="contact">

      <!--google map start-->
      <section class="google-map">
          <div class="map" id="google-map" data-address="{{ conf.google_maps_address }}"></div>
      </section>
      <!--google map end-->

      <!--contacts form start-->

      <div class="form-container">
          <div class="container">
              {% include 'content/partials/contact_form.html' %}
              <div class="contacts-info">
                  <div class="contact-wrap">
                      <p><b>Контактный телефон: </b></p>
                      <p>{{ conf.phone }}</p>
                  </div>
                  <div class="contact-wrap">
                      <p><b>E-mail: </b></p>
                      <p><a href="mailto:{{ conf.email }}">{{ conf.email }}</a></p>
                  </div>
                  <div class="contact-wrap">
                      <p><b>Адрес: </b></p>
                      <p>{{ conf.address }}</p>
                  </div>
              </div>
          </div>


      </div>

      <!--contacts form end-->
  </section>
  <!--contacts end-->
  {% endif %}

  {% include 'content/partials/popup_form.html' %}
  {% include 'content/partials/popup_response_form.html' %}

{% endblock %}

{% block scripts %}
  <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDlgAx5uM4UtPMSzDaVToeNGqe9uNZqRP4"></script>
  {{ block.super }}
{% endblock %}

content/templates/content/portfolio.html
{% extends "base.html" %}

{% block left_menu %}
{% endblock %}
{% block content %}
  <!--project description section start-->

  <section class="gallery-section">
      <div class="gallery-section__desc-bg">
          <div class="container">

              <div class="gallery-section__desc-block desc-block">
                  <p class="desc-block__release">Дата релиза {{ portfolio.release_date }}</p>
                  <h1>{{ portfolio.name }}</h1>
                  {% if portfolio.url %}
                  <h2><a href="{{ portfolio.url }}" target="_blank">{{ portfolio.url }}</a></h2>
                  {% endif %}

                  <div>
                      <p><b>Краткое описание проекта:</b> {{ portfolio.short_description }}
                      </p>

                      <p><b>Подробное описание проекта:</b> {{ portfolio.detailed_description }}
                      </p>
                  </div>
              </div>

              <div class="gallery-section__gallery-nav gallery-nav">
                {% if prev_portfolio != None %}
                <a href="{{ prev_portfolio }}" class="gallery-nav__arrow gallery-nav__arrow--prev">Назад</a>
                {% endif %}
                <a href="#!" class="gallery-section__btn pop-up-form-open" data-project-id="{{ portfolio.id }}">Заказать проект</a>
                {% if next_portfolio != None %}
                <a href="{{ next_portfolio }}" class="gallery-nav__arrow gallery-nav__arrow--next">Вперед</a>
                {% endif %}

              </div>

          </div>
      </div>

      <!--screenshots start-->
      <div class="gallery-screenshots">
          <div class="container">
              {% for image in portfolio.images.all %}
                <div class="screentshot">
                  <a href="#!" class="screenshot-btn"><img src="{{ image.image.url }}" alt="screenshot"></a>
                </div>
              {% endfor %}
          </div>

          <!-- TODO: screenshot popup dynamic -->
          <!--screenshot pop up start-->

          <div class="screenshot-popup">
              <div class="container">
                  <div class="screenshot-popup__img-wrap">
                      <a href="#!" class="screenshot-popup__close">X</a>
                      <div class="screenshot-popup__img">
                          <img src="" alt="" id="full-screenshot-img">
                      </div>
                  </div>
              </div>
          </div>

          <!--screenshot pop up end-->
      </div>
      <!--screenshots end-->

  </section>
  <!--project description section end-->
  {% include 'content/partials/popup_form.html' %}
  {% include 'content/partials/popup_response_form.html' %}
{% endblock %}

content/templates/content/portfolio_list.html
{% extends "base.html" %}

{% block content %}
  <!--portfolio start-->
  <section class="portfolio-section portfolio-section--full">
      <div class="container">
          <div class="portfolio">
            {% for item in portfolio_list %}
              <div class="portfolio__project project">
                  <p class="project__img shadow" style="background-image:url({{ item.image.url }})"></p>
                  <div class="project__info">
                      <p class="project__info__title">{{ item.name }}</p>
                      <p class="project__info__text">{{ item.short_description }}</p>
                      <p class="project__btns">
                          <a href="{{ item.get_absolute_url }}" class="project__btn project__btn-more">Посмотреть</a>
                          <a href="#!" class="project__btn project__btn-buy pop-up-form-open" data-project-id="{{ item.id }}"></a>
                      </p>
                  </div>
              </div>
            {% endfor %}

            {% if is_paginated %}
              <div class="portfolio__navigation">
                <a href="{% if page_obj.has_previous %}?page={{ page_obj.previous_page_number }}{% endif %}" class="portfolio__navigation__arrows portfolio__navigation__arrows--prev {% if not page_obj.has_previous %}not-active{% endif %}"></a>
              <div class="portfolio__pagination">
                {% for page in paginator.page_range %}
                <a href="?page={{ page }}" class="portfolio__pagination-link portfolio__pagination{% if page_obj.number == page %}--active{% endif %}">{{ page }}</a>
                {% endfor %}
              </div>
                <a href="{% if page_obj.has_next %}?page={{ page_obj.next_page_number }}{% endif %}" class="portfolio__navigation__arrows portfolio__navigation__arrows--next {% if not page_obj.has_next %}not-active{% endif %}"></a>
              </div>
            {% endif %}
          </div>

      </div>
  </section>

  <!--portfolio end-->
  {% include 'content/partials/popup_form.html' %}
  {% include 'content/partials/popup_response_form.html' %}
{% endblock %}